trigger: none
stages:
    - stage: AzureCLI
      displayName: 'Azure CLI'
      jobs:
      - job: AzureCLIScript
        displayName: 'Azure CLI Script'
        pool:
          vmImage: 'ubuntu-latest'
          steps:
          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Azure subscription 1 (98134baf-b89e-45c5-9c70-1c40e593e6db)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                #!/bin/bash
                
                # Install Terraform
                echo "Installing Terraform..."
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp.gpg
                echo "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
                sudo apt-get update && sudo apt-get install terraform
                
                # Initialize Terraform
                echo "Initializing Terraform..."
                terraform init
                
                # Apply Terraform configuration
                echo "Applying Terraform configuration..."
                terraform apply -auto-approve