trigger:
- none

pool:
  vmImage: windows-latest

steps:

- powershell: |
    Write-Host $(Build.ArtifactStagingDirectory)
    # Get-ChildItem -Path $(Build.ArtifactStagingDirectory) -Recurse -Force        
    
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- checkout: self
  displayName: 'Checkout repository'
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    workingDirectory: '$(Build.SourcesDirectory)'    
    command: 'init'
    backendServiceArm: 'Azure subscription 1 (98134baf-b89e-45c5-9c70-1c40e593e6db)'
    backendAzureRmResourceGroupName: 'rg-sharedresources-dev-01'
    backendAzureRmStorageAccountName: 'stsharedresdevnsure01'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'rg-communicationhub-dev-01.tfstate'

- task: TerraformTaskV4@4
  displayName: 'Terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure subscription 1 (98134baf-b89e-45c5-9c70-1c40e593e6db)'
    commandOptions: '-out=tfplan'

- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'tfplan -auto-approve'
    environmentServiceNameAzureRM: 'Azure subscription 1 (98134baf-b89e-45c5-9c70-1c40e593e6db)'