trigger:
- none

pool:
  vmImage: windows-latest

stages:
  - stage: Chechov_validate
    jobs:
    - job: Compliance
      displayName: 'Run Checkov to validate Terraform'

      steps:
      - script: |   
          pip3 install checkov
        displayName: 'Get tools'
      
      - script:
          checkov --directory '$(Build.SourcesDirectory)\Infrastructure\rg-communicationhub-dev-01'
        workingDirectory: '$(Build.SourcesDirectory)\Infrastructure\rg-communicationhub-dev-01'
        displayName: 'Run Chechov'
        continueOnError: true

  - stage: Deploy_Terraform
    jobs:
    - job: Deploy
      displayName: 'Validate and deploy Terraform'

      steps:
      - task: TerraformInstaller@1
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: 'latest'

      - checkout: self
        displayName: 'Checkout repository'
      - task: TerraformTaskV4@4
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          workingDirectory: '$(Build.SourcesDirectory)/Infrastructure/rg-communicationhub-dev-01'    
          command: 'init'
          backendServiceArm: 'Azure subscription 1 (98134baf-b89e-45c5-9c70-1c40e593e6db)'
          backendAzureRmResourceGroupName: 'rg-sharedresources-dev-01'
          backendAzureRmStorageAccountName: 'stsharedresdevnsure01'
          backendAzureRmContainerName: 'terraformstate'
          backendAzureRmKey: 'rg-communicationhub-dev-01.tfstate'

      - task: TerraformTaskV4@4
        displayName: 'Terraform validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'

      - task: TerraformTaskV4@4
        displayName: 'Terraform Plan'
        inputs:
          provider: 'azurerm'
          workingDirectory: '$(Build.SourcesDirectory)/Infrastructure/rg-communicationhub-dev-01'
          command: 'plan'
          environmentServiceNameAzureRM: 'Azure subscription 1 (98134baf-b89e-45c5-9c70-1c40e593e6db)'
          commandOptions: '-out=tfplan'

      - task: TerraformTaskV4@4
        displayName: 'Terraform Apply'
        inputs:
          provider: 'azurerm'
          workingDirectory: '$(Build.SourcesDirectory)/Infrastructure/rg-communicationhub-dev-01'
          command: 'apply'    
          environmentServiceNameAzureRM: 'Azure subscription 1 (98134baf-b89e-45c5-9c70-1c40e593e6db)'

      # - task: TerraformTaskV4@4
      #   displayName: 'Terraform Destroy'
      #   inputs:
      #     provider: 'azurerm'
      #     workingDirectory: '$(Build.SourcesDirectory)/Infrastructure/rg-communicationhub-dev-01'
      #     command: 'destroy'    
      #     environmentServiceNameAzureRM: 'Azure subscription 1 (98134baf-b89e-45c5-9c70-1c40e593e6db)'