trigger: none
stages:
    - stage: Terrascan_validate
      jobs:
      - job: Compliance
        displayName: 'Run Terrascan to check for compliance'
        pool: 
          vmImage: 'ubuntu-latest'
      
        steps:
        - script: |
            curl --location https://github.com/accurics/terrascan/releases/download/v1.3.1/terrascan_1.3.1_Linux_x86_64.tar.gz --output terrascan.tar.gz
            tar -xvf terrascan.tar.gz
            sudo install terrascan /usr/local/bin    
          displayName: 'Get tools'

        - script: |
            terrascan scan
          workingDirectory: '$(System.DefaultWorkingDirectory)/PipelineTesting'
          displayName: 'Run terrascan'
          continueOnError: true

    - stage: TFSEC_validate
      jobs:
      - job: Compliance
        displayName: 'Run tfsec to check for compliance'
        pool: 
          vmImage: 'ubuntu-latest'   
      
        steps:
        - script: |
            curl -L -o tfsec https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64
            chmod +x tfsec
            sudo mv tfsec /usr/local/bin/
          displayName: 'Get tools'

        - script: |
            tfsec
          workingDirectory: '$(System.DefaultWorkingDirectory)/PipelineTesting'
          displayName: 'Run tfsec'
          continueOnError: true

    - stage: Checkov_validate
      jobs:
      - job: Compliance
        displayName: 'Run Checkov to check for compliance'
        pool: 
          vmImage: 'ubuntu-latest'
      
        steps:
        - script: |   
            pip3 install checkov
          displayName: 'Get tools'
        
        - script:
            checkov --directory '$(System.DefaultWorkingDirectory)/PipelineTesting'
          workingDirectory: '$(System.DefaultWorkingDirectory)/PipelineTesting'
          displayName: 'Run Chechov'
          continueOnError: true
