trigger: none
stages:
    - stage: validate
      jobs:
      - job: Compliance
        displayName: 'Run Terrascan to check for compliance'
        pool: 
          vmImage: 'ubuntu-latest'
      
        steps:
        - script: |
            curl --location https://github.com/accurics/terrascan/releases/download/v1.3.1/terrascan_1.3.1_Linux_x86_64.tar.gz --output terrascan.tar.gz
            tar -xvf terrascan.tar.gz
            sudo install terrascan /usr/local/bin    
          displayName: 'Get tools'

        - script: |
            echo '$(System.DefaultWorkingDirectory)'
            terrascan scan -t azure -i terraform --output junit-json > $(System.DefaultWorkingDirectory)Terrascan-Report.xml
          workingDirectory: '$(System.DefaultWorkingDirectory)/PipelineTesting'
          displayName: 'Run terrascan'             
 